version: '3.7'
services:
  # image: '865143743213.dkr.ecr.eu-central-1.amazonaws.com/tmb-front:latest'
  nginx-react:
    container_name: 'tmb-front'
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      # env_file:
      #   - ../envs/tmb-front.env
    ports:
      - 3000:80
    # extra_hosts:
    #   - 'host.docker.internal:host-gateway'
  # logging:
  #   driver: awslogs
  #   options:
  #     awslogs-region: eu-central-1
  #     awslogs-group: tmb-front
  #     awslogs-create-group: 'true'
  #     tag:
  #       '{{.Name}}_{{ with split .ImageName ":" }}{{index . 1}}{{end}}_{{.ID}}'
