#!/bin/bash
cd /home/ubuntu/tmb-front
aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 865143743213.dkr.ecr.eu-central-1.amazonaws.com
docker-compose pull
docker-compose up -d --force-recreate